/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as ApiHelloRouteImport } from './routes/api/hello'
import { Route as mainRegisterIndexRouteImport } from './routes/(main)/register.index'
import { Route as mainLoginIndexRouteImport } from './routes/(main)/login.index'
import { Route as mainAboutIndexRouteImport } from './routes/(main)/about.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as mainPostPostIdRouteImport } from './routes/(main)/post.$postId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRegisterIndexRoute = mainRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainLoginIndexRoute = mainLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAboutIndexRoute = mainAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => mainRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const mainPostPostIdRoute = mainPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/hello': typeof ApiHelloRoute
  '/': typeof mainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/post/$postId': typeof mainPostPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/about': typeof mainAboutIndexRoute
  '/login': typeof mainLoginIndexRoute
  '/register': typeof mainRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/hello': typeof ApiHelloRoute
  '/': typeof mainIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/post/$postId': typeof mainPostPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/about': typeof mainAboutIndexRoute
  '/login': typeof mainLoginIndexRoute
  '/register': typeof mainRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/hello': typeof ApiHelloRoute
  '/(main)/': typeof mainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(main)/post/$postId': typeof mainPostPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(main)/about/': typeof mainAboutIndexRoute
  '/(main)/login/': typeof mainLoginIndexRoute
  '/(main)/register/': typeof mainRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/hello'
    | '/'
    | '/dashboard/'
    | '/post/$postId'
    | '/api/auth/$'
    | '/about'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/hello'
    | '/'
    | '/dashboard'
    | '/post/$postId'
    | '/api/auth/$'
    | '/about'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/(main)'
    | '/dashboard'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/hello'
    | '/(main)/'
    | '/dashboard/'
    | '/(main)/post/$postId'
    | '/api/auth/$'
    | '/(main)/about/'
    | '/(main)/login/'
    | '/(main)/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHelloRoute: typeof ApiHelloRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/api/hello': {
      id: '/api/hello'
      path: '/api/hello'
      fullPath: '/api/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/register/': {
      id: '/(main)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof mainRegisterIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/login/': {
      id: '/(main)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof mainLoginIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/about/': {
      id: '/(main)/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainAboutIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/post/$postId': {
      id: '/(main)/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof mainPostPostIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainPostPostIdRoute: typeof mainPostPostIdRoute
  mainAboutIndexRoute: typeof mainAboutIndexRoute
  mainLoginIndexRoute: typeof mainLoginIndexRoute
  mainRegisterIndexRoute: typeof mainRegisterIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainPostPostIdRoute: mainPostPostIdRoute,
  mainAboutIndexRoute: mainAboutIndexRoute,
  mainLoginIndexRoute: mainLoginIndexRoute,
  mainRegisterIndexRoute: mainRegisterIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHelloRoute: ApiHelloRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
